export const theme = {
    primary_color: "#FC4b08",
    secondary_color: "#FF7C39",
    tertiary_color: "#FFA460",
    white: "#FFF",
    gray: "#999",
    gray_md: "#EDEDF0",
    gray_lg: "#F5F5F5",
    alert_color: "#FF0C37",
    dark_color: "#272727",
    font_family: "'Montserrat', sans-serif",
    base_font_size: "1rem",
    h1_font_size: "2.8rem",
    h2_font_size: "2rem",
    h3_font_size: "1.5rem",
    h4_font_size: "1.125rem",
    inner_padding: "90px 0px",
    inner_padding_md: "70px 0px",
    inner_padding_sm: "50px 0px",
    inner_padding_xs: "30px 0px",
}